### ISSUE TITLE
CI / CD of the community API through a Jenkins pipeline to our regular docker infrastructure

### ISSUE THREAD

**Issue by bertolla** [noi-techpark/it.bz.noi.community-api#2]
**UPDATE**
As we decided today (2021-09-06) we no longer use Lambda.

- [x] @toburger adapts the code and scripts for the regular docker installations (removes all lambda specific code)
- [x] @toburger updates the project to have it similar to the odh-api-core project
- [x] @toburger updates the README to describe all ENV vars and adds missing chapters (if any)
- [ ] @alexlanz creates ci pipeline
- [ ] @alexlanz creates pipeline for testing environment
- [ ] @alexlanz creates pipeline for production environment

related to noi-techpark/bdp-core#203

**Comment by Piiit** [comment]
@alexlanz @toburger  I rephrase this issue to no longer use Lambda, but deployment to our regular docker infrastructure...

**Comment by Piiit** [comment]
@alexlanz @toburger please write here, if I have forgotten something

**Comment by toburger** [comment]
Hi @Piiit, can you give me more rights to this project? I can't check your task list checkpoints nor can I assign labels or assignees to PRs and/or issues.

**Comment by Piiit** [comment]
@toburger Done, please check...

**Comment by toburger** [comment]
Still can't check the task checkboxes. The other things work.

**Comment by RudiThoeni** [comment]
ci + testing cd created
